---
    - name: Install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
    - name: Install nginx
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: Lighthouse | Install git
      become: true
      ansible.builtin.yum:
        name: git
        state: present
    - name: Lighthouse | Clone repository
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_url }}"
        dest: "{{ lighthouse_dir }}"
        version: master
    - name: Create Lighthouse config
      become: true
      ansible.builtin.template:
        src: nginx_lighthouse.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0755
        backup: true
      notify: nginx restarted

      